// project1.3/project1.3/project1/frontend/src/views/teacher/KnowledgeTree.vue
<template>
  <div style="max-width: 1200px; margin: 0 auto;">
    <n-space align="center" style="margin-bottom: 8px;">
      <n-button text @click="$router.push('/dashboard')">
        <template #icon><n-icon><arrow-back-outline /></n-icon></template>
        返回首页
      </n-button>
    </n-space>
    <n-space justify="space-between" style="margin-bottom: 16px;">
      <n-h2 style="margin: 0;">知识树 — {{ materialName }}</n-h2>
      <n-space>
        <n-button type="primary" :loading="extracting" @click="extract" v-if="!nodes.length">
          提取知识树
        </n-button>
        <n-button @click="extract" :loading="extracting" v-else>重新提取</n-button>
        <n-button type="info" @click="goGenerateExam" :disabled="!selectedNodes.length">
          用选中知识点组卷 ({{ selectedNodes.length }})
        </n-button>
      </n-space>
    </n-space>

    <n-spin :show="loading">
      <n-grid cols="2" :x-gap="12">
        <n-grid-item>
          <n-card title="知识点结构" size="small">
            <KnowledgeTreePanel :nodes="nodes" @update:checked-keys="onCheck" />
          </n-card>
        </n-grid-item>
        <n-grid-item>
          <n-card title="节点详情" size="small" v-if="selectedNode">
            <n-descriptions :column="1" bordered size="small">
              <n-descriptions-item label="名称">{{ selectedNode.name }}</n-descriptions-item>
              <n-descriptions-item label="类型">{{ selectedNode.node_type }}</n-descriptions-item>
              <n-descriptions-item label="定义">{{ selectedNode.definition || '无' }}</n-descriptions-item>
              <n-descriptions-item label="术语">{{ (selectedNode.key_terms || []).join(', ') || '无' }}</n-descriptions-item>
              <n-descriptions-item label="重点">{{ selectedNode.teaching_emphasis || '无' }}</n-descriptions-item>
            </n-descriptions>
          </n-card>
          <n-empty v-else description="点击左侧节点查看详情" style="margin-top: 60px;" />
        </n-grid-item>
      </n-grid>
    </n-spin>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useMessage } from 'naive-ui'
import { ArrowBackOutline } from '@vicons/ionicons5'
import { knowledgeApi } from '../../api/knowledge.js'
import { materialApi } from '../../api/materials.js'
import KnowledgeTreePanel from '../../components/KnowledgeTreePanel.vue'

const route = useRoute()
const router = useRouter()
const message = useMessage()

const materialId = parseInt(route.params.materialId)
const materialName = ref('')
const nodes = ref([])
const selectedNodes = ref([])
const selectedNode = ref(null)
const loading = ref(false)
const extracting = ref(false)

onMounted(async () => {
  try {
    const mat = await materialApi.get(materialId)
    materialName.value = mat.data.filename
    const res = await knowledgeApi.getTree(materialId)
    nodes.value = res.data
  } catch (e) { /* no tree yet */ }
})

async function extract() {
  extracting.value = true
  try {
    await knowledgeApi.extract(materialId)
    message.success('知识树提取完成')
    const res = await knowledgeApi.getTree(materialId)
    nodes.value = res.data
  } catch (e) {
    message.error('提取失败: ' + (e.response?.data?.detail || e.message))
  } finally {
    extracting.value = false
  }
}

function onCheck(keys) {
  selectedNodes.value = keys
}

function goGenerateExam() {
  router.push({
    path: '/exams/create',
    query: { nodeIds: selectedNodes.value.join(',') }
  })
}
</script>

// frontend/src/pages/KnowledgeTree.tsx
import { useEffect, useMemo, useState } from 'react'
import { Button, Card, Descriptions, Input, Select, Space, Spin, Typography, message } from 'antd'
import { useParams, Link } from 'react-router-dom'
import type { KnowledgeNode } from '../types'
import { extractTree, getTree, updateNode, deleteTree } from '../api/knowledge'
import { listMaterials } from '../api/materials'
import ScopeTree from '../components/ScopeTree'

export default function KnowledgeTreePage() {
  const { materialId } = useParams()
  const [materials, setMaterials] = useState<Array<{ id: number; filename: string }>>([])
  const [current, setCurrent] = useState<number | null>(materialId ? Number(materialId) : null)
  const [tree, setTree] = useState<KnowledgeNode[]>([])
  const [loading, setLoading] = useState(false)
  const [extracting, setExtracting] = useState(false)
  const [selected, setSelected] = useState<KnowledgeNode | null>(null)

  useEffect(() => {
    listMaterials().then(setMaterials)
  }, [])

  useEffect(() => {
    if (materialId) setCurrent(Number(materialId))
  }, [materialId])

  const loadTree = async (mid: number) => {
    setLoading(true)
    try {
      setTree(await getTree(mid))
      setSelected(null)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    if (current) loadTree(current)
  }, [current])

  async function handleExtract() {
    if (!current) return
    setExtracting(true)
    try {
      const res = await fetch(`/api/knowledge/extract/${current}`, { method: 'POST' })
      if (!res.ok) {
        const data = await res.json().catch(() => ({}))
        throw new Error(data.detail || `提取失败 (${res.status})`)
      }
      message.success('提取完成')
      await loadTree(current)
    } catch (e) {
      message.error((e as Error).message)
    } finally {
      setExtracting(false)
    }
  }

  async function handleReextract() {
    if (!current) return
    await deleteTree(current)
    await handleExtract()
  }

  async function saveSelected() {
    if (!selected) return
    await updateNode(selected.id, {
      name: selected.name,
      definition: selected.definition,
      key_terms: selected.key_terms,
      teaching_emphasis: selected.teaching_emphasis,
      solution_steps: selected.solution_steps,
    })
    message.success('已保存')
    if (current) await loadTree(current)
  }

  const detail = useMemo(() => selected, [selected])

  return (
    <Space direction="vertical" style={{ width: '100%' }} size="middle">
      <Card size="small">
        <Space wrap>
          <Select
            style={{ width: 300 }}
            placeholder="选择材料"
            value={current}
            onChange={(v) => setCurrent(v)}
            options={materials.map((m) => ({ value: m.id, label: m.filename }))}
          />
          <Button type="primary" loading={extracting} disabled={!current} onClick={handleExtract}>
            提取知识树
          </Button>
          <Button disabled={!current} onClick={handleReextract}>
            重新提取
          </Button>
        </Space>
      </Card>
      <div style={{ display: 'flex', gap: 16 }}>
        <Card title="知识树" style={{ width: 380, flexShrink: 0 }} loading={loading}>
          {tree.length ? (
            <ScopeTree
              nodes={tree}
              selectedKeys={selected ? [selected.id] : []}
              onSelect={(keys) => {
                const id = keys[0]
                const flat: KnowledgeNode[] = []
                const walk = (nodes: KnowledgeNode[]) => {
                  nodes.forEach((n) => {
                    flat.push(n)
                    walk(n.children)
                  })
                }
                walk(tree)
                setSelected(flat.find((n) => n.id === id) ?? null)
              }}
            />
          ) : (
            <Typography.Text type="secondary">
              尚无知识树。选择材料后点「提取知识树」。
            </Typography.Text>
          )}
        </Card>
        <Card title="节点详情" style={{ flex: 1 }}>
          {detail ? (
            <Space direction="vertical" style={{ width: '100%' }} size="small">
              <Descriptions size="small" column={2}>
                <Descriptions.Item label="类型">{detail.node_type}</Descriptions.Item>
                <Descriptions.Item label="名称">
                  <Input
                    value={detail.name}
                    onChange={(e) => setSelected({ ...detail, name: e.target.value })}
                  />
                </Descriptions.Item>
              </Descriptions>
              <Typography.Text type="secondary">概念定义</Typography.Text>
              <Input.TextArea
                rows={2}
                value={detail.definition ?? ''}
                onChange={(e) => setSelected({ ...detail, definition: e.target.value })}
              />
              <Typography.Text type="secondary">专业术语（逗号分隔）</Typography.Text>
              <Input
                value={(detail.key_terms ?? []).join(', ')}
                onChange={(e) =>
                  setSelected({
                    ...detail,
                    key_terms: e.target.value.split(/[,，]/).map((s) => s.trim()).filter(Boolean),
                  })
                }
              />
              <Typography.Text type="secondary">解题步骤</Typography.Text>
              <Input.TextArea
                rows={3}
                value={detail.solution_steps ?? ''}
                onChange={(e) => setSelected({ ...detail, solution_steps: e.target.value })}
              />
              <Typography.Text type="secondary">教学重点</Typography.Text>
              <Input.TextArea
                rows={2}
                value={detail.teaching_emphasis ?? ''}
                onChange={(e) => setSelected({ ...detail, teaching_emphasis: e.target.value })}
              />
              <Button type="primary" onClick={saveSelected}>
                保存修改
              </Button>
            </Space>
          ) : (
            <Typography.Text type="secondary">在左侧选择一个知识点查看与编辑。</Typography.Text>
          )}
        </Card>
      </div>
    </Space>
  )
}
